// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPsfQW0D8hLLCV-tHltJUTmLZauyUBLhE',
    appId: '1:1008946912347:web:766b7647629fb6af3db37e',
    messagingSenderId: '1008946912347',
    projectId: 'chathtk-27ead',
    authDomain: 'chathtk-27ead.firebaseapp.com',
    storageBucket: 'chathtk-27ead.firebasestorage.app',
    measurementId: 'G-4Y9X285CSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5EySTVptSV8xLCfWN_YPeJAUOeotVHc0',
    appId: '1:1008946912347:android:433543d0e823d91c3db37e',
    messagingSenderId: '1008946912347',
    projectId: 'chathtk-27ead',
    storageBucket: 'chathtk-27ead.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2KnErXeAs5YnIOcEJKL-TaNDYXu47pE',
    appId: '1:1008946912347:ios:bda7b8779e5c63663db37e',
    messagingSenderId: '1008946912347',
    projectId: 'chathtk-27ead',
    storageBucket: 'chathtk-27ead.firebasestorage.app',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR2KnErXeAs5YnIOcEJKL-TaNDYXu47pE',
    appId: '1:1008946912347:ios:bda7b8779e5c63663db37e',
    messagingSenderId: '1008946912347',
    projectId: 'chathtk-27ead',
    storageBucket: 'chathtk-27ead.firebasestorage.app',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPsfQW0D8hLLCV-tHltJUTmLZauyUBLhE',
    appId: '1:1008946912347:web:31dd79b043d601f53db37e',
    messagingSenderId: '1008946912347',
    projectId: 'chathtk-27ead',
    authDomain: 'chathtk-27ead.firebaseapp.com',
    storageBucket: 'chathtk-27ead.firebasestorage.app',
    measurementId: 'G-KPK1LQLQYY',
  );

}